const todos = [
  {
    id: 1,
    title: "Learn React",
    description: "Understand the basics of React, including components, state, and props.",
    completed: false,
    createdAt: 1672531200000,
    updatedAt: null,
    dueDate: "2025-01-15",
    priority: "high",
    tags: ["frontend", "react"],
    editing: false,
    editText: "",
  },
  {
    id: 2,
    title: "Build a Todo App",
    description: "Create a functional Todo app with features like adding, editing, and deleting tasks.",
    completed: true,
    createdAt: 1672617600000,
    updatedAt: 1672704000000,
    dueDate: null,
    priority: "medium",
    tags: ["project", "todo-app"],
    editing: false,
    editText: "",
  },
  {
    id: 3,
    title: "Write Documentation",
    description: "Document project features, APIs, and setup instructions for better team understanding.",
    completed: false,
    createdAt: 1672790400000,
    updatedAt: null,
    dueDate: "2025-01-20",
    priority: "low",
    tags: ["documentation"],
    editing: false,
    editText: "",
  },
  {
    id: 4,
    title: "Fix Bugs in API",
    description: "Resolve critical API bugs affecting data retrieval and processing.",
    completed: false,
    createdAt: 1672876800000,
    updatedAt: null,
    dueDate: "2025-01-25",
    priority: "high",
    tags: ["backend", "API"],
    editing: false,
    editText: "",
  },
  {
    id: 5,
    title: "Update Portfolio",
    description: "Add recent projects and achievements to your personal portfolio website.",
    completed: true,
    createdAt: 1672963200000,
    updatedAt: 1673049600000,
    dueDate: null,
    priority: "medium",
    tags: ["portfolio"],
    editing: false,
    editText: "",
  },
  {
    id: 6,
    title: "Research New Frameworks",
    description: "Explore emerging frontend and backend frameworks for potential project use.",
    completed: false,
    createdAt: 1673049600000,
    updatedAt: null,
    dueDate: null,
    priority: "low",
    tags: ["research", "frameworks"],
    editing: false,
    editText: "",
  },
  {
    id: 7,
    title: "Attend Team Meeting",
    description: "Discuss project progress, challenges, and upcoming deadlines with the team.",
    completed: true,
    createdAt: 1673136000000,
    updatedAt: 1673222400000,
    dueDate: "2025-01-10",
    priority: "high",
    tags: ["meetings", "team"],
    editing: false,
    editText: "",
  },
  {
    id: 8,
    title: "Design New Feature",
    description: "Create wireframes and prototypes for the new feature being added to the app.",
    completed: false,
    createdAt: 1673222400000,
    updatedAt: null,
    dueDate: "2025-02-01",
    priority: "high",
    tags: ["design", "feature"],
    editing: false,
    editText: "",
  },
  {
    id: 9,
    title: "Write Blog Post",
    description: "Share insights and learnings about a recent project in a blog post.",
    completed: true,
    createdAt: 1673308800000,
    updatedAt: 1673395200000,
    dueDate: null,
    priority: "medium",
    tags: ["blog", "writing"],
    editing: false,
    editText: "",
  },
  {
    id: 10,
    title: "Prepare Presentation",
    description: "Create slides and practice delivery for an upcoming presentation.",
    completed: false,
    createdAt: 1673395200000,
    updatedAt: null,
    dueDate: "2025-01-18",
    priority: "high",
    tags: ["presentation", "work"],
    editing: false,
    editText: "",
  },
  {
    id: 11,
    title: "Update Server Configurations",
    description: "Modify server settings to enhance performance and security.",
    completed: false,
    createdAt: 1673481600000,
    updatedAt: null,
    dueDate: "2025-01-15",
    priority: "medium",
    tags: ["backend", "servers"],
    editing: false,
    editText: "",
  },
  {
    id: 12,
    title: "Optimize Database Queries",
    description: "Improve database query performance to reduce load times.",
    completed: true,
    createdAt: 1673568000000,
    updatedAt: 1673654400000,
    dueDate: null,
    priority: "high",
    tags: ["database", "optimization"],
    editing: false,
    editText: "",
  },
  {
    id: 13,
    title: "Learn GraphQL",
    description: "Study the fundamentals of GraphQL and its integration with a frontend stack.",
    completed: false,
    createdAt: 1673654400000,
    updatedAt: null,
    dueDate: null,
    priority: "low",
    tags: ["frontend", "graphql"],
    editing: false,
    editText: "",
  },
  {
    id: 14,
    title: "Clean Up Codebase",
    description: "Refactor and remove unused code to improve maintainability.",
    completed: false,
    createdAt: 1673740800000,
    updatedAt: null,
    dueDate: "2025-01-25",
    priority: "medium",
    tags: ["refactoring", "cleanup"],
    editing: false,
    editText: "",
  },
  {
    id: 15,
    title: "Test New Features",
    description: "Conduct thorough testing on newly implemented features.",
    completed: false,
    createdAt: 1673827200000,
    updatedAt: null,
    dueDate: "2025-01-30",
    priority: "high",
    tags: ["testing", "features"],
    editing: false,
    editText: "",
  },
  {
    id: 16,
    title: "Set Up CI/CD Pipeline",
    description: "Implement continuous integration and deployment for streamlined workflows.",
    completed: false,
    createdAt: 1673913600000,
    updatedAt: null,
    dueDate: "2025-02-10",
    priority: "high",
    tags: ["devops", "CI/CD"],
    editing: false,
    editText: "",
  },
  {
    id: 17,
    title: "Brainstorm App Ideas",
    description: "Generate new ideas for potential mobile or web applications.",
    completed: true,
    createdAt: 1674000000000,
    updatedAt: 1674086400000,
    dueDate: null,
    priority: "low",
    tags: ["ideas", "brainstorming"],
    editing: false,
    editText: "",
  },
  {
    id: 18,
    title: "Collaborate on New Project",
    description: "Work with a team to kickstart a new project and set goals.",
    completed: false,
    createdAt: 1674086400000,
    updatedAt: null,
    dueDate: "2025-01-28",
    priority: "medium",
    tags: ["collaboration", "project"],
    editing: false,
    editText: "",
  },
  {
    id: 19,
    title: "Deploy Production Build",
    description: "Prepare and deploy the app's production-ready version.",
    completed: false,
    createdAt: 1674172800000,
    updatedAt: null,
    dueDate: "2025-02-05",
    priority: "high",
    tags: ["deployment", "production"],
    editing: false,
    editText: "",
  },
  {
    id: 20,
    title: "Create Style Guide",
    description: "Develop a consistent style guide for the app's design elements.",
    completed: true,
    createdAt: 1674259200000,
    updatedAt: 1674345600000,
    dueDate: null,
    priority: "medium",
    tags: ["design", "style-guide"],
    editing: false,
    editText: "",
  },
];

export default todos;
